### ISSUE TITLE
tacacs package no longer in official CentOS/RHEL repos

### ISSUE THREAD

**Issue by jameskirsop** [fxcm/sethlyons-tac_plus#14]
It seems that the tacacs package has been pulled from the mainstream centos repos recently (though I can't find when).

I've got systems built late last year that installed `tacacs` fine:
```
Installed Packages
Name        : tacacs
Arch        : x86_64
Version     : F4.0.4.28
Release     : 6fb
Size        : 1.0 M
Repo        : installed
Summary     : TACACS+ Daemon
License     : Cisco
Description : Tacacs+ Daemon for Linux
```

`Repo: installed` suggests that it's no longer found anywhere.

This module needs to be updated to point to a supported package (and repo)

**Comment by jameskirsop** [comment]
Alternatively, the (now archived) [Facebook fork](https://github.com/facebookarchive/tac_plus) - which I'm reasonably certain was the source of the RHEL/CentOS package still builds on CentOS 7. I'll try CentOS 8 soon.

Could be easy enough to build an RPM and install it...?

**Comment by sethlyons** [comment]
i don't think this requires an update in the module. `$package_name` in the `params` manifest can be set to install a package of your choice.  many users of this modules build their own RPM and host it in an internal RPM repo.  they then use `$package_name` to install that RPM.

**Comment by jameskirsop** [comment]
8 months later and I still think, at the very least, adding an optional `source` param so that we could specify a path to a local rpm would be helpful. hosting an internal RPM repo for a single rpm is, [as the CentOS docs suggest](https://wiki.centos.org/HowTos/CreateLocalRepos), a lot of overhead.

Using the File resource and getting storing the rpm locally for installation and passing that to `Package => Source` within this module would be helpful.

**Comment by sethlyons** [comment]
added in #15
